### ISSUE TITLE
PaddleServing依赖的openssl是什么版本？1.0版本么？

### ISSUE THREAD

**Issue by wadefelix** [PaddlePaddle/Serving#1040]
基于`nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04`，操作如下

`pip3 isntall paddle-serving-client`竟然只是0.2.1版本😓，只好`pip3 install -i https://mirror.baidu.com/pypi/simple https://paddle-serving.bj.bcebos.com/whl/paddle_serving_client-0.0.0-cp38-none-any.whl`重新安装（对了，这个cp38，还不在https://github.com/PaddlePaddle/Serving/blob/v0.4.0/doc/LATEST_PACKAGES.md 显示呢）。
然后，
```
Traceback (most recent call last):
  File "text_classify_service.py", line 17, in <module>
    from paddle_serving_app.reader.imdb_reader import IMDBDataset
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_app/reader/__init__.py", line 15, in <module>
    from .image_reader import ImageReader, File2Image, URL2Image, Sequential, Normalize, Base64ToImage
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_app/reader/image_reader.py", line 17, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```
 😓
按照https://github.com/baidu/lac/issues/108 使用`apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev`安装必要依赖后，又遇到
```
Traceback (most recent call last):
  File "text_classify_service.py", line 17, in <module>
    from paddle_serving_app.reader.imdb_reader import IMDBDataset
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_app/reader/__init__.py", line 15, in <module>
    from .image_reader import ImageReader, File2Image, URL2Image, Sequential, Normalize, Base64ToImage
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_app/reader/image_reader.py", line 24, in <module>
    from shapely.geometry import Polygon
ModuleNotFoundError: No module named 'shapely'
```
继续使用`pip3 install shapely  -i https://mirror.baidu.com/pypi/simple`安装依赖后，总算运行起来了 👏🏻
执行`curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"words": "i am very sad | 0"}], "fetch":["prediction"]}' http://127.0.0.1:9292/imdb/prediction`，😖服务端又又又又
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_server_gpu/web_service.py", line 217, in init
    self._launch_web_service()
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_server_gpu/web_service.py", line 167, in _launch_web_service
    self.client = Client()
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_client/__init__.py", line 139, in __init__
    from .serving_client import PredictorRes
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory
```

但是ubuntu已经安装了openssl，有libcrypt.so.1.1.0文件的。版本不一致，先软链下试一试
```bash
/usr/lib/x86_64-linux-gnu/
ln -s libcrypto.so.1.1 libcrypto.so.10
ln -s libssl.so.1.1 libssl.so.10
```
还是遇到错误
```
ImportError: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1.0.1_EC' not found (required by /usr/local/lib/python3.8/dist-packages/paddle_serving_client/serving_client.so)
```
这个，看来还是需要openssl 1.0版本的。

ubuntu16上才是1.0版本的openssl，但是ubuntu16又难以安装paddle2.0.0，这就😓了。

**Comment by bjjwwang** [comment]
1.0.2K
我打在这个包里，可以设置到LD_LIBRARY_PATH当中
```
wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar
```

**Comment by wadefelix** [comment]
> 1.0.2K
> 我打在这个包里，可以设置到LD_LIBRARY_PATH当中
> 
> ```
> wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar
> ```

我用ubuntu，毕竟nv钦定。

还有，https://github.com/PaddlePaddle/Serving/blob/v0.5.0/doc/DOCKER_IMAGES_CN.md 的问题，
`docker pull hub.baidubce.com/paddlepaddle/serving:latest-cuda11-cudnn8` 拉取不到镜像的。

**Comment by bjjwwang** [comment]
0.5.0目前还在开发中，非devel镜像还没完全固定
建议 拉取 registry.baidubce.com/paddlepaddle/serving:0.5.0-cuda11-cudnn8-devel

**Comment by bjjwwang** [comment]
> > 1.0.2K
> > 我打在这个包里，可以设置到LD_LIBRARY_PATH当中
> > ```
> > wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar
> > ```
> 
> 我用ubuntu，毕竟nv钦定。
> 
> 还有，https://github.com/PaddlePaddle/Serving/blob/v0.5.0/doc/DOCKER_IMAGES_CN.md 的问题，
> `docker pull hub.baidubce.com/paddlepaddle/serving:latest-cuda11-cudnn8` 拉取不到镜像的。

libcrypto.so和libssl.so用这个就可以了，ubuntu也可以用。因为兼顾到centos和ubuntu同时可用，因此原版ubuntu镜像会在这两个so文件上有出入。
不然就需要自己编译，这样也是可以的

**Comment by TeslaZhao** [comment]
@wadefelix paddle Serving v0.5版本已发布，欢迎试用，已经支持Ubuntu镜像：
https://github.com/PaddlePaddle/Serving/blob/develop/doc/DOCKER_IMAGES_CN.md
