### ISSUE TITLE
sentencepiece0.1.83版本过低在python3.8中安装失败

### ISSUE THREAD

**Issue by nblib** [PaddlePaddle/Serving#1072]
如题,paddle-serving-app==0.3.0依赖的sentencepiece版本在python3.8中安装失败
* python: 3.8.5 
* paddle-serving-app: 0.3.0
* sentencepiece: 0.1.83
````
Collecting sentencepiece==0.1.83
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/hewe/miniconda3/envs/python3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2jsz91ft/sentencepiece_00334083bc7d4ada8f5348fb8ad91b80/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2jsz91ft/sentencepiece_00334083bc7d4ada8f5348fb8ad91b80/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ie2fbv1p
         cwd: /tmp/pip-install-2jsz91ft/sentencepiece_00334083bc7d4ada8f5348fb8ad91b80/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2jsz91ft/sentencepiece_00334083bc7d4ada8f5348fb8ad91b80/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/home/hewe/miniconda3/envs/python3.8/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
```

**Comment by TeslaZhao** [comment]
感谢反馈，我们验证一下

**Comment by bjjwwang** [comment]
可以先 
`python3.8 -m pip install sentencepiece`
然后
`python3.8 -m pip install paddle-serving-app==0.3.0`
