### ISSUE TITLE
执行yolov3模型推理时报错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/Serving#1123]
利用paddledetection训练了yolov3的模型，然后转化为paddle serving的模型
模型链接：https://pan.baidu.com/s/1iETMZ8b6hLppFaT33Oc3pg 
提取码：14ea 

`test_client.py`文件
```
import sys
import numpy as np
from paddle_serving_client import Client
from paddle_serving_app.reader import *
import cv2
preprocess = Sequential([
    File2Image(), BGR2RGB(), Resize(
        (608, 608), interpolation=cv2.INTER_LINEAR), Div(255.0), Transpose(
            (2, 0, 1))
])

postprocess = RCNNPostprocess("label_list.txt", "output", [608, 608])
client = Client()

client.load_client_config("serving_client/serving_client_conf.prototxt")
client.connect(['127.0.0.1:9393'])

im = preprocess(sys.argv[1])
fetch_map = client.predict(
    feed={
        "image": im,
        "im_size": np.array(list(im.shape[1:])),
    },
    fetch=["multiclass_nms_0.tmp_0"])
fetch_map["image"] = sys.argv[1]
postprocess(fetch_map)
```
报错信息
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0409 04:27:36.250483 29111 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:9393"): added 1
Traceback (most recent call last):
  File "../../deploy/serving/test_client.py", line 40, in <module>
    postprocess(fetch_map)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 427, in __call__
    self.clsid2catid)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 350, in _get_bbox_result
    bbox_results = self._bbox2out([result], clsid2catid, is_bbox_normalized)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 313, in _bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 5
```

**Comment by HexToString** [comment]
看到是后处理的问题，请问是使用v0.5.0的版本么？

**Comment by Huihuihh** [comment]
> 看到是后处理的问题，请问是使用v0.5.0的版本么？

我转化的模型是在另一台paddlepaddle==2.0.0版本的机器上转化的，因为用这个1.8.4的paddle转化有问题
```
2021-04-09 02:19:57,150-WARNING: config YOLOv3Loss.batch_size is deprecated, training batch size should be set by TrainReader.batch_size
2021-04-09 02:20:08,161-INFO: save_inference_model pruned unused feed variables im_id
2021-04-09 02:20:08,162-INFO: Export serving model to ./inference_model, client side: ./inference_model/serving_client, server side: ./inference_model/serving_server. input: ['image', 'im_size'], output: ['multiclass_nms_0.tmp_0']...
Traceback (most recent call last):
  File "tools/export_serving_model.py", line 107, in <module>
    main()
  File "tools/export_serving_model.py", line 93, in main
    save_serving_model(FLAGS, exe, feed_vars, test_fetches, infer_prog)
  File "tools/export_serving_model.py", line 55, in save_serving_model
    import paddle_serving_client.io as serving_io
  File "/root/miniconda3/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 24, in <module>
    from paddle.fluid.core import CipherUtils
ImportError: cannot import name 'CipherUtils' from 'paddle.fluid.core_avx' (/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/core_avx.so)
```
```
paddle-serving-app            0.3.0
paddle-serving-client         0.5.0
paddle-serving-server-gpu     0.5.0.post10
paddlehub                     1.8.3
paddlelite                    2.6.3
paddlepaddle-gpu              1.8.4.post107
paddleslim                    1.1.1
paddlex                       1.2.6
x2paddle                      0.8.9
```

**Comment by HexToString** [comment]
我复现一下。

**Comment by Huihuihh** [comment]
> 我复现一下。

突然发现是我自己的问题，我在训练的时候，忘记修改num_classes的值了

**Comment by HexToString** [comment]
可否详细讲述一下num_classes对这个的影响？
以及问题发现的过程。
好为其他的同学提供一些帮助。
方便的话，多谢。

**Comment by Huihuihh** [comment]
怎么说呢，发现的挺巧合的，查看PaddleDetection上的关于serving的使用案例（ https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/deploy/serving ），发现按照案例上训练的模型能够成功执行，然后我将对应的`configs/yolov3_mobilenet_v1_roadsign.yml`文件修改成我自己的数据集训练出来的模型也能够成功使用serving推理，然后突然想起原先训练的时候忘记修改num_classes这个值了，然后修改后，重新训练了一个模型测试，能够成功使用serving推理，所以可以确定是这个num_classes值的问题

**Comment by HexToString** [comment]
多谢您提供的信息，非常感谢。
