### ISSUE TITLE
请教save_dygraph_model问题

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/Serving#1233]
## 环境：
(pd) ➜  pip list | grep paddle
paddle-serving-client 0.5.0
paddle-serving-server 0.5.0
paddlepaddle          2.0.2
## 代码：
resnet50 = paddle.vision.models.resnet50
model = resnet50(num_classes=3)
model = paddle.Model(model)
model.prepare(optimizer=paddle.optimizer.Momentum(learning_rate=0.001, momentum=0.9, parameters=model.parameters()),
                loss= nn.CrossEntropyLoss(),
                metrics=paddle.metric.Accuracy())
callback = paddle.callbacks.VisualDL(log_dir='visualdl_log_dir')
model.fit(train_dataset, epochs=100, batch_size=10, verbose=1, callbacks=callback)

model.evaluate(test_dataset, batch_size=10, verbose=1)

model.predict(test_dataset, batch_size=10)

serving_io.save_dygraph_model("serving_model", "client_conf", model)

## 错误信息：
Predict begin...
step 1/1 [==============================] - 129ms/step
Predict samples: 2
Traceback (most recent call last):
  File "/Users/ouyang/app/paddle2/ArKnight_Main_Screen_Classify/train.py", line 31, in <module>
    serving_io.save_dygraph_model("serving_model", "client_conf", model)
  File "/opt/anaconda3/envs/pd/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 36, in save_dygraph_model
    paddle.jit.save(model, "serving_tmp")
  File "<decorator-gen-60>", line 2, in save
  File "/opt/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 623, in save
    % type(layer))
TypeError: The input layer of paddle.jit.save should be 'Layer', but received layer type is <class 'paddle.hapi.model.Model'>.

![企业微信20210517-194925](https://user-images.githubusercontent.com/2086862/118483808-0dfb4a00-b749-11eb-815e-ad4074daf3e0.png)

![企业微信20210517-195150](https://user-images.githubusercontent.com/2086862/118484069-63cff200-b749-11eb-8561-608c5881ad9a.png)

**Comment by ouyangshixiong** [comment]
找到[其他](https://aistudio.baidu.com/aistudio/projectdetail/1458673)方法绕过这个坑。
