### ISSUE TITLE
pipeline 方式 0.4.0 报错

### ISSUE THREAD

**Issue by linghaolu** [PaddlePaddle/Serving#1346]
是不是pipeline 方式需要安装 paddle 环境？
但是我安装paddle 1.8 后，依然报错，应该是pipeline的 proxy.so 跟 paddle 环境冲突导致？这种怎么解？
```
ImportError: dlopen: cannot load any more object with static TLS
CRITICAL 2021-08-12 21:52:10,512 [operator.py:1045] [det|1] failed to init op: dlopen: cannot load any more object with static TLS
Traceback (most recent call last):
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle_serving_server/pipeline/operator.py", line 1038, in _run
    concurrency_idx)
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle_serving_server/pipeline/local_service_handler.py", line 137, in get_client
    from paddle_serving_app.local_predict import LocalPredictor
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle_serving_app/local_predict.py", line 22, in <module>
    import paddle.fluid as fluid
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.complex
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/complex/__init__.py", line 15, in <module>
    from . import tensor
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/complex/tensor/__init__.py", line 15, in <module>
    from . import math
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/complex/tensor/math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/fluid/core.py", line 273, in <module>
    raise e
  File "/home/ssd1/work/python3.6/lib/python3.6/site-packages/paddle/fluid/core.py", line 243, in <module>
    from .core_avx import *
ImportError: dlopen: cannot load any more object with static TLS
```

**Comment by bjjwwang** [comment]
这种一般是系统版本比较低或者Python使用的gcc版本比较低导致的。
方便 
```
strings /lib/libc.so | grep GLIBC 
```
的输出
以及python是哪个GCC版本编译的吗

**Comment by linghaolu** [comment]
> 这种一般是系统版本比较低或者Python使用的gcc版本比较低导致的。
> 方便
> 
> ```
> strings /lib/libc.so | grep GLIBC 
> ```
> 
> 的输出
> 以及python是哪个GCC版本编译的吗

后来安装 0.6.0 版本可以了，不过0.6.0版本还是依赖paddle安装包，希望pipeline方式能够去掉对 paddle 安装包的依赖。
