### ISSUE TITLE
部署后执行案例python$ python -m paddle_serving_server.serve --model uci_housing_model --thread 10 --port 9292报错

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/Serving#1412]
完整错误如下：
版本0.6.2
Traceback (most recent call last):
  File "/home/ubuntu01/anaconda3/envs/paddleserving/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/ubuntu01/anaconda3/envs/paddleserving/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/code/paddle/Serving-0.6.2/python/paddle_serving_server/__init__.py", line 17, in <module>
    from . import rpc_service
  File "/home/code/paddle/Serving-0.6.2/python/paddle_serving_server/rpc_service.py", line 20, in <module>
    from .proto import general_model_config_pb2 as m_config
ModuleNotFoundError: No module named 'paddle_serving_server.proto'

paddle版本2.1.0
python3.8
CUDA 10.1 
paddle-serving-server-gpu==0.6.2.post101

**Comment by zhaobinchen** [comment]
请问解决了吗？我在执行以下命令的时候，同样的报错
python3 setup.py.server.in install  \
 --python_version : py37 \
 --device : cpu \ 
 --serving_version : 0.9.0 \
--paddle_version : 2.3.0
