### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Serving#1464]
您好，多并发测试时GRPC 内部报错，无法启动新线程。帮忙看一下，谢谢～

```

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/yangshaoxiong/.conda/envs/py36_paddle2.1/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/yangshaoxiong/.conda/envs/py36_paddle2.1/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yangshaoxiong/.local/lib/python3.6/site-packages/grpc/_server.py", line 875, in _serve
    if not _process_event_and_continue(state, event):
  File "/home/yangshaoxiong/.local/lib/python3.6/site-packages/grpc/_server.py", line 842, in _process_event_and_continue
    concurrency_exceeded)
  File "/home/yangshaoxiong/.local/lib/python3.6/site-packages/grpc/_server.py", line 750, in _handle_call
    thread_pool)
  File "/home/yangshaoxiong/.local/lib/python3.6/site-packages/grpc/_server.py", line 726, in _handle_with_method_handler
    method_handler, thread_pool)
  File "/home/yangshaoxiong/.local/lib/python3.6/site-packages/grpc/_server.py", line 632, in _handle_unary_unary
    method_handler.response_serializer)
  File "/home/yangshaoxiong/.conda/envs/py36_paddle2.1/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/home/yangshaoxiong/.conda/envs/py36_paddle2.1/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/home/yangshaoxiong/.conda/envs/py36_paddle2.1/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by TeslaZhao** [comment]
client报错，还是pipeline server报错？

**Comment by youngstu** [comment]
pipeline server 报错

**Comment by youngstu** [comment]
> client报错，还是pipeline server报错？

pipeline server 报错

**Comment by TeslaZhao** [comment]
已解决

**Comment by youngstu** [comment]
> 已解决

感谢哈。worker_num和concurrency 不需要设置太大，设置太大对实际QPS和响应时间并没有帮助。在GPU利用率没有打满的情况下，适当调大concurrency对QPS提升是有益的。如果GPU利用率打满，再调大concurrency甚至给QPS和响应时间会带来负增益。
