### ISSUE TITLE
模型转换报错

### ISSUE THREAD

**Issue by lululu86** [PaddlePaddle/Serving#1541]
请问各位前辈，我按照文档做图像识别的paddleserving部署时出现了这个错误该如何解决呢？serving/client/serving-app均已安装。

**Comment by lululu86** [comment]
![image](https://user-images.githubusercontent.com/34465212/144161847-d8f88ccb-9528-475f-b32c-22f1624c6b74.png)

**Comment by lululu86** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/paddle_serving_client/convert.py", line 87, in <module>
    fetch_alias_names=args.fetch_alias_names)
  File "/usr/local/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 334, in inference_model_to_serving
    model_filename, params_filename, show_proto, feed_alias_names, fetch_alias_names)
  File "/usr/local/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 214, in save_model
    new_model_file.write(main_program._remove_training_info(False).desc.serialize_to_string())
AttributeError: 'Program' object has no attribute '_remove_training_info'

**Comment by lululu86** [comment]
已解决。环境问题。

**Comment by kaierlong** [comment]
@lululu86 具体是环境哪里出了问题，可以展开一下吗？最近部署的时候也遇到了相同的问题。

**Comment by lululu86** [comment]
> @lululu86 具体是环境哪里出了问题，可以展开一下吗？最近部署的时候也遇到了相同的问题。

paddlepaddle-gpu升到2.2.0,Serving用0.7.0

**Comment by kaierlong** [comment]
@lululu86 多谢，已经解决。应该是paddlepaddle和paddle serving版本有对应关系的，官方应该给出来。

**Comment by lxhmark7** [comment]
paddle的版本问题，之前是paddle2.1,目前升级到2.2,在转换模型不再报错，可以正常运行；
目前，正常运行版本信息 paddlepaddle-gpu-2.2.2post112 + paddle-serving-*-0.8.3
