### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Serving#1627]
用paddle inference 不会报错， 用pipline serving会报错

CRITICAL 2022-02-09 10:46:11,025 [operator.py:1315] [ner|1] failed to init op: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:355)
Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_server/pipeline/operator.py", line 1308, in _run
    concurrency_idx)
  File "/root/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_server/pipeline/local_service_handler.py", line 228, in get_client
    mkldnn_bf16_op_list=self._mkldnn_bf16_op_list)
  File "/root/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle_serving_app/local_predict.py", line 235, in load_model_config
    self.predictor = paddle_infer.create_predictor(config)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:355)

**Comment by TeslaZhao** [comment]
您好，怎么使用的代码，是不是在pipeline框架中import paddle了？

**Comment by ZTurboX** [comment]
> 您好，怎么使用的代码，是不是在pipeline框架中import paddle了？

会用到paddlenlp来处理数据

**Comment by KRuok** [comment]
在使用python pipeline时import paddlex也碰到相同的错误，请问是不能使用pipeline框架时import paddle吗

**Comment by WenmuZhou** [comment]
我也遇到了这个问题，import paddle就会出错
