### ISSUE TITLE
key error during serving the default transformer model

### ISSUE THREAD

**Issue by ghtwht** [PaddlePaddle/Serving#1679]
I trained the default en-de translation transfer model and served it following the schedule you guys recommend but it report the key error as follow:"[2022-02-28 18:02:39,622] ERROR in app: Exception on /transformer/prediction [POST]
Traceback (most recent call last):
  File "/data/venv/paddle/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/venv/paddle/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/venv/paddle/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/venv/paddle/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/venv/paddle/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/venv/paddle/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/venv/paddle/lib/python3.6/site-packages/paddle_serving_server/web_service.py", line 334, in run
    return self.get_prediction(request)
  File "/data/venv/paddle/lib/python3.6/site-packages/paddle_serving_server/web_service.py", line 303, in get_prediction
    feed=request.json["feed"], fetch=fetch, fetch_map=fetch_map)
  File "transformer_web_server.py", line 79, in postprocess
    "save_infer_model/scale_0.tmp_1"]).transpose([0, 2, 1])
KeyError: 'save_infer_model/scale_0.tmp_1'"
 The error refers to the paddle serving module, and I cannot figure out whats going on.

**Comment by TeslaZhao** [comment]
show me the schedule

**Comment by TeslaZhao** [comment]
Hi，The fetch key save_infer_model/scale_0.tmp_1 is not exist in predicting result. So you can add the real fetch which has predicting result in the prototxt to the client.py.
