### ISSUE TITLE
higherHRNet 模型部署测试出错: ValueError: Wrong feed name: im_shape.

### ISSUE THREAD

**Issue by Victoria-1** [PaddlePaddle/Serving#1703]
修改配置文件自己训练了一个higherHRNet模型，infer没问题（根据实际修改过），模型导出也没问题，部署测试时报错：
`root@ubuntu:/home/project/strabismus_detection/output_inference/higherhrnet_hrnet_w32_512# python3 ../../deploy/serving/test_client.py ../../deploy/serving/label_list.txt ../../demo/0000015.jpg
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0309 00:16:40.764921 22318 naming_service_thread.cpp:202] brpc::policy::ListNamingService("127.0.0.1:9393"): added 1
../../deploy/serving/test_client.py ../../deploy/serving/label_list.txt ../../demo/0000015.jpg
Traceback (most recent call last):
  File "../../deploy/serving/test_client.py", line 41, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/dist-packages/paddle_serving_client/client.py", line 366, in predict
    raise ValueError("Wrong feed name: {}.".format(key))
ValueError: Wrong feed name: im_shape.
`

serving_client_conf.prototxt配置文件如下：
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
fetch_var {
  name: "bilinear_interp_v2_1.tmp_0"
  alias_name: "bilinear_interp_v2_1.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 6
}
fetch_var {
  name: "top_k_v2_0.tmp_0"
  alias_name: "top_k_v2_0.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 6
  shape: 30
}
fetch_var {
  name: "top_k_v2_0.tmp_1"
  alias_name: "top_k_v2_0.tmp_1"
  is_lod_tensor: false
  fetch_type: 0
  shape: 1
  shape: 6
  shape: 30
}
fetch_var {
  name: "unsqueeze2_0.tmp_0"
  alias_name: "unsqueeze2_0.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 6
  shape: 1
}

label_list.txt文件在最后一行添加了自己的类别名

环境：虚拟机ubuntu20.04, cpu部署，paddle_serving版本0.8.3，0.7.0均测试过，出现同样问题，请问是什么原因？谢谢

**Comment by Victoria-1** [comment]
已经解决了，这个test_client.py 是根据样例中的模型去设置的参数，里面的preproce， feed中的内容需要根据infer_cfg.yml参数去修改，fetch的内容则需要根据serving_client_conf.prototxt的内容去修改。第一次部署，纯无脑根据样例去跑。。。。
