### ISSUE TITLE
服务端模型预测报错AttributeError: 'paddle.fluid.core_avx.PaddleInferPredictor' object has no attribute 'rrun'

### ISSUE THREAD

**Issue by tfft2126** [PaddlePaddle/Serving#1727]
flask 启动的服务器，客户端post请求过来后报错了，请问这是什么原因呢？和版本有关系吗，paddle的版本是2.2.2，paddel-serving-server,paddel-serving-app是0.8.3,
[2022-03-18 14:57:42,669] ERROR in app: Exception on /rec/prediction [POST]
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Program Files\Python37\lib\site-packages\paddle_serving_server\web_service.py", line 356, in run
    return self.get_prediction(request)
  File "D:\Program Files\Python37\lib\site-packages\paddle_serving_server\web_service.py", line 301, in get_prediction
    feed=feed, fetch=fetch, batch=is_batch)
  File "D:\Program Files\Python37\lib\site-packages\paddle_serving_app\local_predict.py", line 392, in predict
    self.predictor.rrun()
AttributeError: 'paddle.fluid.core_avx.PaddleInferPredictor' object has no attribute 'rrun'

**Comment by TeslaZhao** [comment]
File "D:\Program Files\Python37\lib\site-packages\paddle_serving_app\local_predict.py", line 392, in predict
self.predictor.rrun()

您的代码rrun()是不对的，应改成run()，我看paddle serving v0.8.3版本代码里是正确的。

**Comment by tfft2126** [comment]
> File "D:\Program Files\Python37\lib\site-packages\paddle_serving_app\local_predict.py", line 392, in predict self.predictor.rrun()
> 
> 您的代码rrun()是不对的，应改成run()，我看paddle serving v0.8.3版本代码里是正确的。

谢谢回答，确实是自己改错了
