### ISSUE TITLE
About stopping  the server problems

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Serving#1738]
在关闭服务的时候，因为是nohup方式启动的，所以最初用了kill -9 XXX的方式
后来用了  `python -m paddle_serving_server.serve stop`方式进行停止，报下面的异常

`/home/beyond/myDL/miniconda3/lib/python3.7/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but prior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/home/beyond/myDL/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/beyond/myDL/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/beyond/myDL/miniconda3/lib/python3.7/site-packages/paddle_serving_server/serve.py", line 535, in <module>
    result = stop_serving(args.server)
  File "/home/beyond/myDL/miniconda3/lib/python3.7/site-packages/paddle_serving_server/serve.py", line 451, in stop_serving
    infoList = load_pid_file(filepath)
  File "/home/beyond/myDL/miniconda3/lib/python3.7/site-packages/paddle_serving_server/util.py", line 123, in load_pid_file
    "ProcessInfo.json file is not exists, All processes of PaddleServing has been stopped.")
ValueError: ProcessInfo.json file is not exists, All processes of PaddleServing has been stopped.`

后台服务进程依然在
![1648540617(1)](https://user-images.githubusercontent.com/12640462/160562334-e6101c20-50de-46bb-99a7-6df65f5f6186.png)

这种情况是不是只能手动Kill 服务了

**Comment by TeslaZhao** [comment]
收到反馈，已经在排查中。

**Comment by BeyondYourself** [comment]
@TeslaZhao 这个问题怎么样了目前
