### ISSUE TITLE
pipeline server init error

### ISSUE THREAD

**Issue by wenjin11** [PaddlePaddle/Serving#1779]
Traceback (most recent call last):
  File "C:\Users\666\anaconda3\lib\site-packages\paddle_serving_server\pipeline\error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "C:\Users\666\anaconda3\lib\site-packages\paddle_serving_server\pipeline\error_catch.py", line 163, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\666\anaconda3\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 51, in init_helper
    self._dag_executor = dag.DAGExecutor(response_op, dag_conf, worker_idx)
  File "C:\Users\666\anaconda3\lib\site-packages\paddle_serving_server\pipeline\dag.py", line 85, in __init__
    self._tracer = PerformanceTracer(
  File "C:\Users\666\anaconda3\lib\site-packages\paddle_serving_server\pipeline\profiler.py", line 45, in __init__
    self._data_buffer = multiprocessing.Manager().Queue()
  File "C:\Users\666\anaconda3\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Users\666\anaconda3\lib\multiprocessing\managers.py", line 554, in start
    self._process.start()
  File "C:\Users\666\anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\666\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\666\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\666\anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\666\anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Classname: PipelineServicer.__init__.<locals>.init_helper
FunctionName: init_helper

**Comment by TeslaZhao** [comment]
您好，请在 Windows环境下安装 Linux docker，在Docker中部署 Paddle Serving
