### ISSUE TITLE
window 启动serving RuntimeError:     An attempt has been made to start a new process before the   

### ISSUE THREAD

**Issue by litter-rabbit** [PaddlePaddle/Serving#1836]
Traceback (most recent call last):
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\site-packages\paddle_serving_server\pipeline\error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\site-packages\paddle_serving_server\pipeline\error_catch.py", line 163, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\site-packages\paddle_serving_server\pipeline\pipeline_server.py", line 51, in init_helper
    self._dag_executor = dag.DAGExecutor(response_op, dag_conf, worker_idx)
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\site-packages\paddle_serving_server\pipeline\dag.py", line 86, in __init__
    self._is_thread_op, tracer_interval_s, server_worker_num)
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\site-packages\paddle_serving_server\pipeline\profiler.py", line 45, in __init__
    self._data_buffer = multiprocessing.Manager().Queue()
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\multiprocessing\managers.py", line 563, in start
    self._process.start()
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\CDROG\paddle_recaptcha\env\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Classname: PipelineServicer.__init__.<locals>.init_helper
FunctionName: init_helper

**Comment by w5688414** [comment]
I meet the same problem, have you solved this problem?
