### ISSUE TITLE
在ma c上运行Serving/examples/Pipeline/PaddleDetection/faster_rcnn异常

### ISSUE THREAD

**Issue by ddgetget** [PaddlePaddle/Serving#1868]
```
paddle_serving_server.pipeline.error_catch.CustomException: 
	exception_code: 3003
	exception_type: INIT_ERROR
	error_msg: pipeline server init error
	is_send_to_user: False
Traceback (most recent call last):
  File "web_service.py", line 77, in <module>
    fasterrcnn_service.run_service()
  File "/Users/geng/opt/miniconda3/envs/ppdet/lib/python3.8/site-packages/paddle_serving_server/web_service.py", line 69, in run_service
    self._server.run_server()
  File "/Users/geng/opt/miniconda3/envs/ppdet/lib/python3.8/site-packages/paddle_serving_server/pipeline/pipeline_server.py", line 314, in run_server
    PipelineServicer(self._name, self._response_op, self._conf),
  File "/Users/geng/opt/miniconda3/envs/ppdet/lib/python3.8/site-packages/paddle_serving_server/pipeline/pipeline_server.py", line 57, in __init__
    raise CustomException(CustomExceptionCode.INIT_ERROR, "pipeline server init error")
paddle_serving_server.pipeline.error_catch.CustomException: 
	exception_code: 3003
	exception_type: INIT_ERROR
	error_msg: pipeline server init error
	is_send_to_user: False
```

**Comment by SunVenus** [comment]
我也遇到这个问题了，请问解决了吗？
