### ISSUE TITLE
win部署问题

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/Serving#1875]
python ocr_debugger_server.py cpu &
This API will be deprecated later. Please do not use it
I1028 09:21:40.265446 10692 analysis_predictor.cc:985] ir_optim is turned off, no IR pass will be executed
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : relu_2.tmp_0  size: 29491200
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : batch_norm_31.tmp_3  size: 29491200
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : tmp_2  size: 22118400
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : x  size: 11059200
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : conv2d_186.tmp_0  size: 5529600
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : relu_1.tmp_0  size: 7372800
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : elementwise_add_3  size: 1382400
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : elementwise_add_7  size: 806400
I1028 09:21:40.296638 10692 memory_optimize_pass.cc:216] Cluster name : conv2d_179.tmp_0  size: 345600
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I1028 09:21:40.327919 10692 analysis_predictor.cc:1035] ======= optimize end =======
I1028 09:21:40.327919 10692 naive_executor.cc:102] ---  skip [feed], feed -> x
I1028 09:21:40.327919 10692 naive_executor.cc:102] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
This API will be deprecated later. Please do not use it
web service address:
http://192.168.1.107:9292/ocr/prediction
This API will be deprecated later. Please do not use it
 * Serving Flask app "paddle_serving_server.web_service" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
然后就不动了。。。死住了

安装的paddlegpu2.3.2, cuda11.6 
小白按照Windows平台使用Paddle Serving指导 操作，到python ocr_debugger_server.py cpu & 就卡住了。
请问什么问题？怎么解决

**Comment by cunjing56** [comment]
> 

意思是，忽略，下一步？

**Comment by cunjing56** [comment]
下一步也是报错
(paddle) F:\pkg\Serving\examples\C++\PaddleOCR\ocr>python ocr_web_client.py
Traceback (most recent call last):
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\http\client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\http\client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\http\client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\http\client.py", line 1036, in _send_output
    self.send(msg)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\http\client.py", line 976, in send
    self.connect()
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000151FB960508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\requests\adapters.py", line 499, in send
    timeout=timeout,
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9292): Max retries exceeded with url: /ocr/prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151FB960508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ocr_web_client.py", line 38, in <module>
    r = requests.post(url=url, headers=headers, data=json.dumps(data))
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\SoftProgram\Anaconda3\envs\paddle\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9292): Max retries exceeded with url: /ocr/prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151FB960508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
