### ISSUE TITLE
执行python3 pipeline_http_client.py报错

### ISSUE THREAD

**Issue by guomengf** [PaddlePaddle/Serving#1884]
服务器安装环境：
paddle-bfloat         0.1.2
paddle-serving-app    0.9.0
paddle-serving-client 0.9.0
paddle-serving-server 0.9.0
paddlepaddle          2.0.0rc0

房产价格那个测试可用通过，但是验证ocr这个执行python3 pipeline_http_client.py就报错
INFO 2022-11-15 07:16:31,534 [pipeline_server.py:64] (log_id=0) inference request name:ocr self.name:ocr time:1668496591.5340307
INFO 2022-11-15 07:16:31,534 [operator.py:1826] RequestOp unpack one request. log_id:0, clientip:             name:ocr, method:prediction, time:1668496591.5349097
INFO 2022-11-15 07:16:31,535 [dag.py:379] (data_id=1 log_id=0) Succ Generate ID 
ERROR 2022-11-15 07:16:31,659 [error_catch.py:106] 
Log_id: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server/pipeline/error_catch.py", line 160, in wrapper
    raise CustomException(CustomExceptionCode.INPUT_PARAMS_ERROR, "invalid arg list: {}".format(invalid_argument_list), True)
paddle_serving_server.pipeline.error_catch.CustomException: 
	exception_code: 5000
	exception_type: INPUT_PARAMS_ERROR
	error_msg: invalid arg list: ['feed_batch', 'fetch_list']
	is_send_to_user: True
Classname: Op.process.<locals>.feed_fetch_list_check_helper
FunctionName: feed_fetch_list_check_helper
Args: ([{'x': array([[[[ 2.2489083 ,  2.2489083 ,  2.2489083 , ..., -1.5699117 ,
          -1.5699117 , -1.5699117 ],
         [ 2.2489083 ,  2.2489083 ,  2.2489083 , ..., -1.7582841 ,
          -1.7411593 , -1.689785  ],
         [ 2.2489083 ,  2.2489083 ,  2.2489083 , ..., -1.6726602 ,
          -1.5870365 , -1.5185375 ],
         ...,
         [ 0.27956173,  0.19393796,  0.07406469, ..., -0.86779684,
          -0.93629587, -0.9534206 ],
         [ 0.41655976,  0.29668647,  0.17681322, ..., -0.85067207,
          -0.9020463 , -0.93629587],
         [ 0.45080924,  0.38231024,  0.33093598, ..., -0.83354735,
          -0.86779684, -0.8849216 ]],

        [[ 2.4285715 ,  2.4285715 ,  2.4285715 , ..., -1.352941  ,
          -1.352941  , -1.352941  ],
         [ 2.4285715 ,  2.4285715 ,  2.4285715 , ..., -1.5455183 ,
          -1.5280112 , -1.4754901 ],
         [ 2.4285715 ,  2.4285715 ,  2.4285715 , ..., -1.4579831 ,
          -1.3704481 , -1.30042   ],
         ...,
         [ 0.62535024,  0.5378152 ,  0.41526622, ..., -0.687675  ,
          -0.757703  , -0.77521   ],
         [ 0.7303923 ,  0.6078432 ,  0.48529422, ..., -0.67016804,
          -0.72268903, -0.77521   ],
         [ 0.74789923,  0.6778712 ,  0.62535024, ..., -0.652661  ,
          -0.687675  , -0.72268903]],

        [[ 2.6399999 ,  2.6399999 ,  2.6399999 , ..., -0.95041394,
          -0.95041394, -0.9678431 ],
         [ 2.6399999 ,  2.6399999 ,  2.6399999 , ..., -1.1595643 ,
          -1.142135  , -1.0898474 ],
         [ 2.6399999 ,  2.6399999 ,  2.6399999 , ..., -1.0724183 ,
          -0.98527235, -0.89812636],
         ...,
         [ 1.0539434 ,  0.9667975 ,  0.84479314, ..., -0.37525052,
          -0.44496727, -0.46239647],
         [ 1.1585187 ,  1.0365143 ,  0.93193907, ..., -0.35782132,
          -0.4275381 , -0.46239647],
         [ 1.193377  ,  1.1236603 ,  1.0713726 , ..., -0.3403921 ,
          -0.37525052, -0.4101089 ]]]], dtype=float32)}], ['save_infer_model/scale_0.tmp_1'])
ERROR 2022-11-15 07:16:31,660 [operator.py:1101] [det] failed to predict. Log_id: 1  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
INFO 2022-11-15 07:16:31,660 [operator.py:1488] prometheus inf count +1
ERROR 2022-11-15 07:16:31,665 [dag.py:420] (data_id=1 log_id=0) Failed to predict: [det] failed to predict. Log_id: 1  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.

**Comment by guomengf** [comment]
重新下载这两个zip包，再次尝试就可用了
python -m paddle_serving_app.package --get_model ocr_rec
tar -xzvf ocr_rec.tar.gz
python -m paddle_serving_app.package --get_model ocr_det
tar -xzvf ocr_det.tar.gz
