### ISSUE TITLE
KeyError: 'concat_8.tmp_0.lod'

### ISSUE THREAD

**Issue by ddgetget** [PaddlePaddle/Serving#1896]
使用PaddleDetection套件，数据集使用VOC2007转换成COCO数据集后，采用fast_RCNN模型进行训练，导出模型后，在Serving的docker环境下部署，采用PaddleDetection/C++的方式，服务端能够启动，客户端启动之后出现
```
λ 0697a0a4f727 /home/inference_model/faster_rcnn_r50_fpn_2x_coco/faster_rcnn_r50_fpn_2x_coco python3 test_client.py 009046.jpg 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1220 18:03:05.789144   325 naming_service_thread.cpp:202] brpc::policy::ListNamingService("127.0.0.1:9494"): added 1
I1220 18:03:10.932313   325 general_model.cpp:490] [client]logid=0,client_cost=5119.43ms,server_cost=5086.37ms.
Traceback (most recent call last):
  File "test_client.py", line 54, in <module>
    postprocess(fetch_map)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_app/reader/image_reader.py", line 427, in __call__
    self.clsid2catid)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_app/reader/image_reader.py", line 344, in _get_bbox_result
    lod = [fetch_map[fetch_name + '.lod']]
KeyError: 'concat_8.tmp_0.lod'
```

**Comment by fanruifeng** [comment]
你好 这个问题解决了嘛, 我目前也是这个问题

**Comment by ddgetget** [comment]
这个问题无解，c的代码我也无法使用，我用了flask，自己写了一个服务

**Comment by fanruifeng** [comment]
哦哦， 那你用 python pipline的部署方式, 实现了嘛

**Comment by fanruifeng** [comment]
哦哦， 那你用 python pipline的部署方式, 实现了嘛

**Comment by fanruifeng** [comment]
哦哦， 那你用 python pipline的部署方式, 实现了嘛

**Comment by fanruifeng** [comment]
哦哦， 那你用 python pipline的部署方式, 实现了嘛

**Comment by fanruifeng** [comment]
哦哦， 那你用 python pipline的部署方式, 实现了嘛
