### ISSUE TITLE
No module named 'paddle.fluid' 

### ISSUE THREAD

**Issue by magicleo** [PaddlePaddle/Serving#1985]
paddle-serving-app        0.9.0
paddle-serving-client     0.9.0
paddle-serving-server-gpu 0.9.0.post112
paddlepaddle-gpu          2.6.0.post112

Traceback (most recent call last):
  File "/mnt/storage/anaconda3/envs/paddle/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/storage/anaconda3/envs/paddle/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/storage/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle_serving_client/convert.py", line 21, in <module>
    from .io import inference_model_to_serving
  File "/mnt/storage/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle_serving_client/io/__init__.py", line 16, in <module>
    from paddle.fluid import Executor
ModuleNotFoundError: No module named 'paddle.fluid'

新版本的paddle已经没有fluid了。serving什么时候能更新下啊

**Comment by heavengate** [comment]
我们正在排期，有进展会同步过来

**Comment by FrozenZero** [comment]
> 我们正在排期，有进展会同步过来

请问，有没有临时的解决方案呀？我cuda是11.8 + ubuntu18 + paddlepaddle-gpu 0.9.0.post1102+ python 3.9.18+paddlepaddle-gpu 2.6.0.post117 。当我在转换模型的时候也是报上面的错误。报错如下：
Traceback (most recent call last):
  File "/home/yons/miniconda3/envs/ocr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yons/miniconda3/envs/ocr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yons/miniconda3/envs/ocr/lib/python3.9/site-packages/paddle_serving_client/convert.py", line 21, in <module>
    from .io import inference_model_to_serving
  File "/home/yons/miniconda3/envs/ocr/lib/python3.9/site-packages/paddle_serving_client/io/__init__.py", line 16, in <module>
    from paddle.fluid import Executor
ModuleNotFoundError: No module named 'paddle.fluid'

**Comment by entrehuihui** [comment]
还没有进展吗

**Comment by winkinwong** [comment]
半年过去了，还没进展吗？ 有什么解决方案？

**Comment by yazheng0307** [comment]
这个serving库真的一点都没人维护吗，用的真心悸

**Comment by fatsheep2020** [comment]
这个问题是不是还解决不了？

**Comment by wolfplan** [comment]
版本迭代太慢了吧，这个serving库还有人在维护吗？
