### ISSUE TITLE
保存 Serving 模型时出现错误；

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/Serving#818]
保存模型的语句：
`serving_io.save_model("RE_model","RE_client_conf", {"text": str_id}, {"prediction":new_variable},fluid.default_main_program())`
报错信息：
```
Traceback (most recent call last):
  File "./ernie/run_duie.py", line 403, in <module>
    main(args)
  File "./ernie/run_duie.py", line 345, in main
    serving_io.save_model("RE_model","RE_client_conf", {"text": str_id}, {"prediction":new_variable},fluid.default_main_program())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 35, in save_model
    feed_var_names = [feed_var_dict[x].name for x in feed_var_dict]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 35, in <listcomp>
    feed_var_names = [feed_var_dict[x].name for x in feed_var_dict]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 639, in name
    return self._ivar.name
AttributeError: 'Variable' object has no attribute '_ivar'
```
其中 str_id，new_variable的类型均为 <class 'paddle.fluid.framework.Variable'>

**Comment by iceriver97** [comment]
@MRXLT  我在动态图保存时会报上面的错误，静态图保存的话会出现下面的错误：
```
Traceback (most recent call last):
  File "./ernie/run_duie.py", line 401, in <module>
    main(args)
  File "./ernie/run_duie.py", line 343, in main
    serving_io.save_model("RE_model","RE_client_conf", {"text": str_id}, {"prediction":new_variable},fluid.default_main_program())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 47, in save_model
    main_program=main_program)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1026, in save_inference_model
    var, 1., name="save_infer_model/scale_{}".format(i))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 9938, in scale
    name=name, dtype=x.dtype, persistable=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 663, in dtype
    return self.desc.dtype()
AttributeError: 'Variable' object has no attribute 'desc'
```
`/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py`中的代码段如下：
```
    @property
    def name(self):
        if in_dygraph_mode():
            return self._ivar.name
        else:
            return cpt.to_text(self.desc.name())
```

**Comment by iceriver97** [comment]
@MRXLT  环境参数：
paddlehub == 1.6.0         
paddlepaddle-gpu == 1.5.1.post97
python == 3.7

**Comment by iceriver97** [comment]
@MRXLT  升级至 PP1.8.0 后，出现维度问题：
```
Traceback (most recent call last):
  File "./ernie/run_duie.py", line 401, in <module>
    main(args)
  File "./ernie/run_duie.py", line 315, in main
    prediction = predict_wrapper(reader, exe, test_prog, test_pyreader, graph_vars,'final', 'final')
  File "./ernie/run_duie.py", line 385, in predict_wrapper
    res = predict(args, examples, exe, test_prog, test_pyreader, graph_vars)
  File "/home/aistudio/DuIe_baseline/ernie/finetune/relation_extraction_multi_cls.py", line 429, in predict
    exe.run(program=test_program, fetch_list=fetch_list, return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::SequenceUnpadOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/sequence_lod.py", line 1013, in sequence_unpad
    outputs={'Out': out})
  File "/home/aistudio/DuIe_baseline/ernie/finetune/relation_extraction_multi_cls.py", line 169, in create_model
    lod_labels = fluid.layers.sequence_unpad(labels, seq_lens)
  File "./ernie/run_duie.py", line 158, in main
    ernie_config=ernie_config)
  File "./ernie/run_duie.py", line 401, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
Error: The shape of Input(Length) should be [batch_size].
  [Hint: Expected len_dims.size() == 1, but received len_dims.size():2 != 1:1.] at (/paddle/paddle/fluid/operators/sequence_ops/sequence_unpad_op.cc:41)
  [operator < sequence_unpad > error]
```
相关代码如下：
```
 pyreader = fluid.layers.py_reader(
        capacity=50,
        shapes=[[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, args.num_labels],[-1], [-1, 1],
                [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1]],
        dtypes=[
            'int64', 'int64', 'int64', 'int64', 'float32', 'float32', 'int64',
            'int64', 'int64', 'int64'
        ],
        lod_levels=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        name=pyreader_name,
        use_double_buffer=True)

lod_labels = fluid.layers.sequence_unpad(labels, seq_lens)
```

**Comment by MRXLT** [comment]
你好，使用paddle_serving时推荐安装1.8.2以上的版本的paddlepaddle，这里的维度问题可能是因为之前的模型文件是使用较低版本的paddle api编写的与1.8的api有区别，建议检查一下1.8版本的sequence_unpad的使用方式

**Comment by iceriver97** [comment]
@MRXLT 谢谢，我看到了1.8的api 但我找不到1.5api中的sequence_unpad，我在哪里可以找到呢？我想比较一下差异。

**Comment by MRXLT** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#sequence-unpad
paddle文档可以通过左上角的版本号来看不同版本的文档
