### ISSUE TITLE
如何获取 fetch参数？

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/Serving#827]
我将模型 freeze 之后，使用 `inference_model_to_serving `将模型保存为 Serving模型；
但我想知道客户端调用 `client.predict()`函数时，fetch参数应该是什么？
不应该是我在freeze模型时使用函数 `save_inference_model` 时指定的 fetch吗？我将其作为参数得到报错信息：
```
aistudio@jupyter-380628-755201:~$ python ./client.py 983884_sat.jpg 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0907 16:32:14.215747  2107 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:9292"): added 1
Traceback (most recent call last):
  File "./client.py", line 18, in <module>
    fetch_map = client.predict(feed={"image": im}, fetch=["transpose_1.tmp_0"])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_client/__init__.py", line 274, in predict
    "Fetch names should not be empty or out of saved fetch list.")
ValueError: Fetch names should not be empty or out of saved fetch list.
```
我无法打开 serving_client_conf.prototxt 文件，是不是在该文件中可以得到我想要的信息呢？
这里是该文件

[serving_client_conf.zip](https://github.com/PaddlePaddle/Serving/files/5182057/serving_client_conf.zip)
固化模型的代码：
```
fluid.io.save_inference_model(
        cfg.FREEZE.SAVE_DIR,
        feeded_var_names=[image.name],
        target_vars=[logit_out],
        executor=exe,
        main_program=infer_prog,
        model_filename=cfg.FREEZE.MODEL_FILENAME,
        params_filename=cfg.FREEZE.PARAMS_FILENAME)
```
我是不是应该指定client.predict()> fetch = 这里 logit_out.name?

**Comment by iceriver97** [comment]
我是不是应该使用 `inference_model_to_serving` 返回的参数来指定？我发现他好像是可行的，但是我遇到了新的问题：
```
Error: ShapeError: The number of input channels should be equal to filter channels * groups for Op(conv). But received: the input's channels is [1024], the shape of input is [1, 1024, 1024, 3], the filter's channel is [3], the shape of filter is [32, 3, 3, 3], the groups is [1], the data_format is AnyLayout. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:1024 != filter_dims[1] * groups:3.] at (/paddle/paddle/fluid/operators/conv_op.cc:94)
  [operator < conv2d > error]
Aborted (core dumped)
```
我是不是需要对图片做预处理？

**Comment by iceriver97** [comment]
@MRXLT 对于图像分割的模型，我是否能直接使用 curl 的方式来调用服务，而不是通过客户端代码？

**Comment by iceriver97** [comment]
@MRXLT  在对图片做转置后 `im = im.transpose((2, 0, 1))` 会出现：
```
Traceback (most recent call last):
  File "./client.py", line 23, in <module>
    postprocess(fetch_map)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 259, in __call__
    mask_png = mask.reshape((512, 512, 1))
ValueError: cannot reshape array of size 2097152 into shape (512,512,1)
```
这是客户端的代码：
```
from paddle_serving_client import Client
from paddle_serving_app.reader import Sequential, File2Image, Resize, Transpose, BGR2RGB, SegPostprocess
import sys
import cv2
import numpy as np

client = Client()
client.load_client_config("serving_client/serving_client_conf.prototxt")
client.connect(["127.0.0.1:9292"])

preprocess = Sequential(
    [File2Image()])

postprocess = SegPostprocess(19)

filename = sys.argv[1]
im = preprocess(filename)
print(np.shape(im))
im = im.transpose((2, 0, 1))
print(np.shape(im))
fetch_map = client.predict(feed={"image": im}, fetch=["save_infer_model/scale_0"])
fetch_map["filename"] = filename
postprocess(fetch_map)
```

**Comment by MRXLT** [comment]
你好，请问预测结果的shape是多少

**Comment by iceriver97** [comment]
@MRXLT 您好，我查看了一下获得 fetch_map 里面的 save_infer_model/scale_0 ，shape为 （1，2，1024，1024）；
这应该是错误的吧？但是这个模型之前使用的 PaddleSeg 套件，我没有做任何修改；

**Comment by iceriver97** [comment]
@MRXLT 还是说我应该对这个 （2，1024，1024）的数组做一些后处理呢？谢谢

**Comment by iceriver97** [comment]
@MRXLT @TeslaZhao
