### ISSUE TITLE
paddle pgl使用paddle serving进行模型保存的时候，被自动剪枝，导致后面输入的时候模型输入不合法

### ISSUE THREAD

**Issue by xiuechen** [PaddlePaddle/Serving#857]
rt

Traceback (most recent call last):
  File "client.py", line 53, in <module>
    fetch_map = client.predict(feed=feed_dict, fetch=["proba"])
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_client/__init__.py", line 282, in predict
    raise ValueError("Wrong feed name: {}.".format(key))
ValueError: Wrong feed name: sub_graph/edges_dst.

**Comment by MRXLT** [comment]
paddle serving目前暂不支持图神经网络的预测
