### ISSUE TITLE
运行fit_a_line例子报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Serving#952]
我使用的是这个了例子，只是将paddle_serving_server 改为 paddle_serving_server_gpu

https://github.com/PaddlePaddle/Serving/blob/develop/python/examples/fit_a_line/test_server.py

请求命令
```
curl -H "Content-Type:application/json" -X POST -d '{"feed":[{"x": [0.0137, -0.1136, 0.2553, -0.0692, 0.0582, -0.0727, -0.1583, -0.0584, 0.6283, 0.4919, 0.1856, 0.0795, -0.0332]}], "fetch":["price"]}' http://192.168.88.60:9292/uci/prediction
```

服务器日志：
```
[root@8a699d9457d2 serving]# python3 test.py 
This API will be deprecated later. Please do not use it
This API will be deprecated later. Please do not use it
mkdir: cannot create directory ‘workdir’: File exists
This API will be deprecated later. Please do not use it
web service address:
http://172.17.0.2:9292/uci/prediction
This API will be deprecated later. Please do not use it
 * Serving Flask app "paddle_serving_server_gpu.web_service" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Going to Run Comand
/usr/local/lib/python3.6/site-packages/paddle_serving_server_gpu/serving-gpu-trt-0.4.0/serving -enable_model_toolkit -inferservice_path workdir -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 2 -port 12000 -reload_interval_s 10 -resource_path workdir -resource_file resource.prototxt -workflow_path workdir -workflow_file workflow.prototxt -bthread_concurrency 2 -gpuid 0 -max_body_size 67108864 
/usr/local/lib/python3.6/site-packages/paddle_serving_server_gpu/serving-gpu-trt-0.4.0/serving: error while loading shared libraries: libnvinfer.so.6: cannot open shared object file: No such file or directory
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0105 03:52:53.427336  3670 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:12000"): added 1
(1, 1, 13)
W0105 03:52:53.429221  3670 predictor.hpp:129] inference call failed, message: [E112]1/1 channels failed, fail_limit=1 [C0][E111]Fail to connect SocketId=1@127.0.0.1:12000: Connection refused [R1][E112]Fail to select server from list://127.0.0.1:12000 lb=la [R2][E112]Fail to select server from list://127.0.0.1:12000 lb=la
E0105 03:52:53.429270  3670 general_model.cpp:361] failed call predictor with req: insts { tensor_array { float_data: 0.0137 float_data: -0.1136 float_data: 0.2553 float_data: -0.0692 float_data: 0.0582 float_data: -0.0727 float_data: -0.1583 float_data: -0.0584 float_data: 0.6283 float_data: 0.4919 float_data: 0.1856 float_data: 0.0795 float_data: -0.0332 elem_type: 1 shape: 1 shape: 1 shape: 13 } } fetch_var_names: "price" log_id: 0
This API will be deprecated later. Please do not use it
[2021-01-05 03:52:53,429] ERROR in app: Exception on /uci/prediction [POST]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server_gpu/web_service.py", line 223, in run
    return self.get_prediction(request)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server_gpu/web_service.py", line 193, in get_prediction
    feed=request.json["feed"], fetch=fetch, fetch_map=fetch_map)
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_server_gpu/web_service.py", line 269, in postprocess
    for key in fetch_map:
TypeError: 'NoneType' object is not iterable
I0105 03:52:53.529567  3673 socket.cpp:2370] Checking SocketId=0@127.0.0.1:12000
```

**Comment by yeyupiaoling** [comment]
安装了错误的版本，我以为这是GPU的，结果是tensorRT的
```
pip install paddle-serving-server-gpu==0.4.0.100
```

这个才是
```
pip install paddle-serving-server-gpu==0.4.0.post10
```
