### ISSUE TITLE
paddlex训练的model需要怎样转换用于paddleServing？

### ISSUE THREAD

**Issue by meishitouzhele** [PaddlePaddle/Serving#957]
paddlex训练的model需要怎样用于paddleServing？

**Comment by TeslaZhao** [comment]
paddlex训练的模型保存下来，就可以用Serving部署。参考此文档 https://github.com/PaddlePaddle/Serving/blob/develop/doc/SAVE_CN.md

**Comment by meishitouzhele** [comment]
paddlex训练后导出三个文件
__model__
__params__
model.yml
paddleServing是不是只需要__model__这一个？

**Comment by TeslaZhao** [comment]
inference_model_to_serving接口转换成可用于Paddle Serving的模型文件，model和params都需要的

**Comment by meishitouzhele** [comment]
请问是这个吗？把dirname改成文件夹名？将这个存成一个.py文件进行执行？这个接口没用过 请多指教
import paddle_serving_client.io as serving_io
serving_io.inference_model_to_serving(dirname, serving_server="serving_server", serving_client="serving_client",  model_filename=None, params_filename=None)

**Comment by meishitouzhele** [comment]
我通过使用inference_model_to_serving与paddle_serving_client.convert，都报这个提示。。。。。如果能看出问题，麻烦指点下问题方向哈
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "zhuanhuan.py", line 2, in <module>
    serving_io.inference_model_to_serving(dirname="inference_model", serving_server="serving_server", serving_client="serving_client",  model_filename=None, params_filename=None)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_client/io/__init__.py", line 120, in inference_model_to_serving
    fluid.io.load_inference_model(dirname=dirname, executor=exe, model_filename=model_filename, params_filename=params_filename)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 1402, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 928, in load_persistables
    filename=filename)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 805, in load_vars
    executor.run(load_prog)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
8   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
9   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 785, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 928, in load_persistables
    filename=filename)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 1402, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_client/io/__init__.py", line 120, in inference_model_to_serving
    fluid.io.load_inference_model(dirname=dirname, executor=exe, model_filename=model_filename, params_filename=params_filename)
  File "zhuanhuan.py", line 2, in <module>
    serving_io.inference_model_to_serving(dirname="inference_model", serving_server="serving_server", serving_client="serving_client",  model_filename=None, params_filename=None)

----------------------
Error Message Summary:
----------------------
UnavailableError: Load operator fail to open file inference_model/res5a_branch1_weights, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (/paddle/paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

**Comment by TeslaZhao** [comment]
> 请问是这个吗？把dirname改成文件夹名？将这个存成一个.py文件进行执行？这个接口没用过 请多指教
> import paddle_serving_client.io as serving_io
> serving_io.inference_model_to_serving(dirname, serving_server="serving_server", serving_client="serving_client", model_filename=None, params_filename=None)

dirname为模型文件存储的绝对路径

**Comment by meishitouzhele** [comment]
是这样写_model_的绝对路径吗，他自己去找params文件吗？
import paddle_serving_client.io as serving_io
serving_io.inference_model_to_serving(dirname="/home/zxdtest/inference_model/_model_", serving_server="serving_server", serving_client="serving_client",  model_filename=None, params_filename=None)

**Comment by meishitouzhele** [comment]
这样写会提示这样：
λ 767d59d42c62 /home/zxdtest python zhuanhuan.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "zhuanhuan.py", line 2, in <module>
    serving_io.inference_model_to_serving(dirname="/home/zxdtest/inference_model/_model_", serving_server="serving_server", serving_client="serving_client",  model_filename=None, params_filename=None)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle_serving_client/io/__init__.py", line 120, in inference_model_to_serving
    fluid.io.load_inference_model(dirname=dirname, executor=exe, model_filename=model_filename, params_filename=params_filename)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py", line 1374, in load_inference_model
    raise ValueError("There is no directory named '%s'", dirname)
ValueError: ("There is no directory named '%s'", '/home/zxdtest/inference_model/_model_')

**Comment by TeslaZhao** [comment]
默认的model_filename 是 "__model__"；如果不是的话，路径是/home/zxdtest/inference_model/model(确认model不是文件)，把模型文件名写成你的文件名改成下面：

import paddle_serving_client.io as serving_io
serving_io.inference_model_to_serving(dirname="/home/zxdtest/inference_model/model", serving_server="serving_server", serving_client="serving_client", model_filename="model", params_filename="params")

**Comment by meishitouzhele** [comment]
老铁 我又来了  昨天我测试还是不行，应该不是路径的问题，我用另外一个转换也报相同的错误，还有其他方向需要注意吗？

或者你可以使用Paddle Serving提供的名为paddle_serving_client.convert的内置模块进行转换。
python -m paddle_serving_client.convert --dirname ./your_inference_model_dir

**Comment by meishitouzhele** [comment]
感谢老哥

**Comment by meishitouzhele** [comment]
发布自己的model  需要写一个server的启动py文件    这个参考哪个文档？   我目前发布的是图像分类的model，是根据生成的serving_server_conf.prototxt里的参数进行编写服务端启动的.py文件吗？

**Comment by TeslaZhao** [comment]
参考imagenet 或 resnet50:
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/imagenet
https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/resnet_v2_50

**Comment by meishitouzhele** [comment]
好嘞

**Comment by meishitouzhele** [comment]
我参考的imagenet，发布能成功，调用的时候提示如下：
{"result":"Fetch names should not be empty or out of saved fetch list."}
劳烦指导个方向，我去学习解决下。

**Comment by TeslaZhao** [comment]
自己发布的Model要用模型定义feed和fetch参数，看下你生成的*.prototxt文件中

**Comment by meishitouzhele** [comment]
嗯嗯  imagenet.label这个分类名文件，转换的时候没有自动生成，手动添加一个吗

**Comment by meishitouzhele** [comment]
老哥，转换后的模型，我已经成功再centos的docker镜像里成功部署调用了，；相同的内容我再win10上启动api的时候报以下提示，咱们再win上使用需要特殊注意什么吗？
This API will be deprecated later. Please do not use it
This API will be deprecated later. Please do not use it
web service address:
http://192.168.13.226:9292/image/prediction
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\setupfile\python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\setupfile\python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\setupfile\python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\setupfile\python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\setupfile\python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\setupfile\python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\setupfile\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\paddlexwork\servingmodeltest\zxdtwodemo\zxd_web_service.py", line 96, in <module>
    image_service.run_rpc_service()
  File "D:\setupfile\python37\lib\site-packages\paddle_serving_server\web_service.py", line 152, in run_rpc_service
    p_rpc.start()
  File "D:\setupfile\python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\setupfile\python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\setupfile\python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\setupfile\python37\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\setupfile\python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\setupfile\python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by meishitouzhele** [comment]
> 默认的model_filename 是 "**model**"；如果不是的话，路径是/home/zxdtest/inference_model/model(确认model不是文件)，把模型文件名写成你的文件名改成下面：
> 
> import paddle_serving_client.io as serving_io
> serving_io.inference_model_to_serving(dirname="/home/zxdtest/inference_model/model", serving_server="serving_server", serving_client="serving_client", model_filename="model", params_filename="params")

之前我是再centos下转换成功了，请问这个转换方法在win10上能用吗？
