### ISSUE TITLE
模型转换出错

### ISSUE THREAD

**Issue by ponycloud235** [PaddlePaddle/Serving#977]
使用paddlex训练的yolov3_darknet53 模型放置serving部署。
需要做转换，在做转换的时候报错了
转化的命令
`python -m paddle_serving_client.convert --dirname ./model/best_model/ --model_filename="model.pdmodel" --params_filename="model.pdparams"`
模型文件
![image](https://user-images.githubusercontent.com/2733701/105117876-43c85300-5b08-11eb-8444-c5e4bdde192b.png)

报错信息如下
`TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/paddle-serve/env/lib/python3.6/site-packages/paddle_serving_client/convert.py", line 66, in <module>
    params_filename=args.params_filename)
  File "/home/paddle-serve/env/lib/python3.6/site-packages/paddle_serving_client/io/__init__.py", line 120, in inference_model_to_serving
    fluid.io.load_inference_model(dirname=dirname, executor=exe, model_filename=model_filename, params_filename=params_filename)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/io.py", line 1402, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/io.py", line 928, in load_persistables
    filename=filename)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/io.py", line 805, in load_vars
    executor.run(load_prog)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/paddle-serve/env/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::DeserializeFromStream(std::istream&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&)
3   paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>::LoadParamsFromBuffer(paddle::framework::ExecutionContext const&, paddle::platform::Place const&, std::istream*, bool, std::vector<std::string, std::allocator<std::string> > const&) const
4   paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/io.py", line 803, in load_vars
    'model_from_memory': vars_from_memory
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/io.py", line 928, in load_persistables
    filename=filename)
  File "/home/paddle-serve/env/lib64/python3.6/site-packages/paddle/fluid/io.py", line 1402, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/home/paddle-serve/env/lib/python3.6/site-packages/paddle_serving_client/io/__init__.py", line 120, in inference_model_to_serving
    fluid.io.load_inference_model(dirname=dirname, executor=exe, model_filename=model_filename, params_filename=params_filename)
  File "/home/paddle-serve/env/lib/python3.6/site-packages/paddle_serving_client/convert.py", line 66, in <module>
    params_filename=args.params_filename)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: tensor version 1904018048 is not supported, Only version 0 is supported
  [Hint: Expected version == 0U, but received version:1904018048 != 0U:0.] at (/paddle/paddle/fluid/framework/lod_tensor.cc:287)
  [operator < load_combine > error]`

环境基于centos7.6 python3.6 serving0.4 和cuda9.0b版本

**Comment by ponycloud235** [comment]
搞定，模型转换的时候需要指定参数名。 
python3 -m paddle_serving_client.convert --dirname=./model/yolov3 --params_filename="__params__"
